version: '3'

services:
  api_nodejs:
    build: .
    environment:
    - PORT=3000
    volumes:
      - ./:/process
      - /process/node_modules 
    ports:
      - "3000:3000"
    restart: on-failure